[2022-07-08 18:10:12] ERROR Error in File Uploads View Generic!!!
Traceback (most recent call last):
  File "G:\AdventsProduct\V1.1.0\AFS\ConsolFiles\process\views.py", line 129, in get_queryset
    return queryset.filter(tenants_id=tenants_id, groups_id=groups_id, entities_id=entities_id,
  File "C:\Users\user\Envs\django\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\user\Envs\django\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Users\user\Envs\django\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\user\Envs\django\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\user\Envs\django\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\user\Envs\django\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\user\Envs\django\lib\site-packages\django\db\models\sql\query.py", line 1159, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
  File "C:\Users\user\Envs\django\lib\site-packages\django\db\models\sql\query.py", line 1198, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'null' for CharField or join on the field not permitted, perhaps you meant isnull?
[2022-07-09 17:07:44] ERROR Error in Get Target Mapping Details Function!!!
Traceback (most recent call last):
  File "G:\AdventsProduct\V1.1.0\AFS\ConsolFiles\process\views.py", line 858, in get_target_mapping_details
    for file_config in files_config_list:
TypeError: 'NoneType' object is not iterable
[2022-07-09 17:09:36] ERROR Error in Get Target Mapping Details Function!!!
Traceback (most recent call last):
  File "G:\AdventsProduct\V1.1.0\AFS\ConsolFiles\process\views.py", line 858, in get_target_mapping_details
    for file_config in files_config_list:
TypeError: 'NoneType' object is not iterable
[2022-07-09 17:13:52] ERROR Error in Get Target Mapping Details Function!!!
Traceback (most recent call last):
  File "G:\AdventsProduct\V1.1.0\AFS\ConsolFiles\process\views.py", line 858, in get_target_mapping_details
    for file_config in files_config_list:
TypeError: 'NoneType' object is not iterable
[2022-07-09 17:17:12] ERROR Error in Get Target Mapping Details Function!!!
Traceback (most recent call last):
  File "G:\AdventsProduct\V1.1.0\AFS\ConsolFiles\process\views.py", line 858, in get_target_mapping_details
    for file_config in files_config_list:
TypeError: 'NoneType' object is not iterable
